google/cctz

- README.md
- src/cctz_fmt.cc
- src/cctz_info.cc
- test/cnv_test.cc
Makes this work on OS X.  Closes #1.
> Tzh version 0 support

- Makefile
This adds shared library support in the makefile
> Makefile Shared Library

- CMakeLists.txt
trivial modification to optionally build executable tools.
> Added BUILD_TOOLS option

- BUILD
- WORKSPACE
https://github.com/google/benchmark/blob/master/BUILD.bazel
Ran bazel run -c opt :benchmarks to check functionality.
> Update WORKSPACE; google/benchmark has bazel support

- CMakeLists.txt
- README.md
Add install rules to cctz to fix #82 issue
inspired by the revert commit in #54
> Add CMake install rules

- include/cctz/civil_time.h
aligment -> alignment
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/127)
> Fix a spelling error

- src/time_tool.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/131)
> We choose to pass cctz::civil_second by value.

- src/cctz_benchmark.cc
- src/time_zone_lookup_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/141)
> Test with a new timezone, America/Nuuk, added in 2020a.

- src/zone_info_source.cc
From an Abseil request: https://github.com/abseil/abseil-cpp/issues/694
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/145)
> Adds support for MSVC 32-bit ARM platforms

- src/time_tool.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/147)
> Use the new %ET format specifier in time_tool

- include/cctz/time_zone.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/148)
> Mention 'z' and 'Z' as possible UTC offsets for cctz::parse()

- src/time_zone_info.cc
From https://github.com/abseil/abseil-cpp/issues/744
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/156)
> Fixes a few compile warnings

- src/time_zone_libc.cc
- src/time_zone_lookup_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/159)
> Succumb to the pressure of -Wshadow.

- BUILD
[Here's relevant discussion at bazel-discuss](https://groups.google.com/g/bazel-discuss/c/GlOuxun4BO0) that enlists various approaches for doing this 
and this one appears to be reasonably simple to implement.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/170)
> Exports test suite for all our tests to other Bazel workspaces.

- WORKSPACE
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/192)
> Updates the GoogleTest and Google Benchmark dependencies

- src/time_zone_info.cc
- src/time_zone_lookup.cc
- src/time_zone_lookup_test.cc
This reverts commit 51a847194736f861c031fc89c7b6c351da549705.
Unfortunately, the only current customer for this code is currently
unable to build it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/195)
> Revert "Add basic support for Fuchsia (#189)"

- src/time_tool.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/215)
> Add missing #include <ios> for 'std::left'.

- src/time_zone_lookup.cc
The code can be simplified by using a simpler API 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/223)
> [fuchsia] Simplify the src/time_zone_lookup.cc logic

- src/time_zone_lookup.cc
Bug: chromium:1292951
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/231)
> Fix a signedness conversion warning.

- src/zone_info_source.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/240)
> Fix build on cygwin

- src/time_zone_posix.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/249)
> Correct a spelling mistake

- src/time_zone_fixed.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/250)
> Prefer std::copy_n() over std::copy() where appropriate

- src/time_zone_format.cc
> Use a specific value (500) for _XOPEN_SOURCE

- src/time_zone_format.cc
> Give FreeBSD the same treatment as OpenBSD re _XOPEN_SOURCE

- src/time_zone_info.cc
https://android.googlesource.com/platform/bionic/+blame/refs/heads/main/libc/tzcode/bionic.cpp#248
> Add new tzdata path for Android

- src/time_zone_lookup.cc
Reported by Chromium after
https://github.com/google/cctz/commit/2ebbe0d8a2771f9899839765fe3e651bd2b55382
> Fix -Wsign-compare warning
