examples/example1.cc, examples/example2.cc, examples/example3.cc, examples/example4.cc, examples/hello.cc, src/cctz.h, src/cctz_cnv.cc, src/cctz_fmt.cc, src/cctz_if.h, src/cctz_impl.cc, src/cctz_impl.h, src/cctz_info.cc, src/cctz_info.h, src/cctz_libc.cc, src/cctz_libc.h, test/cnv_test.cc, test/fmt_test.cc, tools/time_tool.cc
This change removes the need for a 128-bit count of nanoseconds that was
defined by the cctz::time_point type. Instead, cctz functions that
accept time_points can accept any time_point of the form:
`std::chrono::time_point<std::chrono::system_clock, D>`
And functions that produce time points, such as MakeTime() and
`MakeTimeInfo()` now return system_clock time points that are a 64-bit
count of seconds.
There is still a "cctz::time_point" alias defined, but that is simply a
shorthand, and it is not defining a new concept.
The advantages of this change are:
- No unnecessary "cctz::time_point" concept.
- No required use of int128 in the interface.
- All time points that users already have are now accepted.
- No need to pass 128-bits of data where the low 64-bits are all zeros.
Misc other …
=> Adds support for system_clock time_points of any duration.

test/BUILD
This makes it possible to compile cctz with the Bazel sandbox.
=> Add gtest-internal-inl.h to textual_headers of gtest.

src/time_zone_info.h
=00:00:00:16.762 149400== Conditional jump or move depends on uninitialised value(s)
==00:00:00:16.762 149400==    at 0x2C002FA: cctz::TimeZoneInfo::BreakTime(std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long, std::ratio<1l, 1l> > > const&) const (time_zone_info.cc:644)
==00:00:00:16.762 149400==    by 0x2BFBEC4: BreakTime (time_zone_impl.h:45)
==00:00:00:16.762 149400==    by 0x2BFBEC4: cctz::time_zone::lookup(std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long, std::ratio<1l, 1l> > > const&) const (time_zone_lookup.cc:29)
==00:00:00:16.762 149400==    by 0x2BF28DA: lookup<std::chrono::duration<long int, std::ratio<1l, 1000000000l> > > (time_zone.h:83)
=> fix valgrind/s Conditional jump or move depends on uninitialised value(s)

src/time_zone_libc.cc
Some implementations of libc (MUSL in this case) #define __tm_zone and
__tm_gmtoff to tm_zone and tm_gmtoff respectively. This causes a
"redefinition of default argument" upon compilation.
TESTING:
//third_party/cctz:civil_time_test PASSED in 2.1s
//third_party/cctz:time_zone_format_test PASSED in 4.0s
//third_party/cctz:time_zone_lookup_test PASSED in 3.7s
=> Guard get_offset_abbr() impls in src/time_zone_libc.cc

src/time_zone_info.cc
This declaration of default_factory as extern, but with an initializer,
elicits a warning when compiled using clang.  This declaration is on the
MSVC codepath, but the warning fires when library is built for Windows
using clang-cl.
=> Fix extern declaration of default_factory with initializer

src/time_zone_fixed.cc
The issue should be fixed shortly, but until then.
https://developercommunity.visualstudio.com/comments/114235/view.html
=> Declaring kDigits static to avoid a codegen bug in VS2017.

src/time_zone_format.cc
When built with Clang on Windows, I hit this error:
cctz/src/time_zone_format.cc(51,46):  error: conditional expression is ambiguous; 'size_t' (aka 'unsigned long long') can be converted to 'std::basic_istream<char, std::char_traits<char> >::pos_type' (aka 'fpos<_Mbstatet>') and vice versa
return const_cast<char*>(s) + (input.eof() ? strlen(s) : input.tellg());
=> Fix ambiguous conditional expression w/ Clang+Windows

CMakeLists.txt, README.md
There are 3 distincts commits, I can split the PR if you prefer.
One of the change is a follow up to your comment (removal of getopt):
- https://github.com/google/cctz/pull/54#issuecomment-348040315
The others are cosmetic changes.
=> Update CMake (remove getopt special case)

WORKSPACE
Name chosen to match the one specified for this repo in abseil-cpp/WORKSPACE.
This line is needed to point a fetched copy of abseil-cpp at a fetched copy of this repo as a local_repository.
=> Add a workspace() rule with the project name to the WORKSPACE file

src/time_zone_libc.cc
`__EMSCRIPTEN__` is defined by the emscripten toolchain whichever
compiler it uses internall. ` __asmjs__` and `__wasm__` are defined in
the two different compiler frontends that emscripten can use.
=> Fix native WebAssembly emscripten build

src/time_zone_posix.h
The original code is accepted by many compilers as a compatibility extension with C, but it is not valid C++, and it is trivial to fix.
=> [time_zone_posix.h] Replace invalid "nested anonymous struct" with valid C++

README.md
Grammer Mistake in the Readme Example 'One Giant Leap'
=> Fixed Grammer Mistake in Readme Example 2

src/time_zone_info.cc, src/time_zone_libc.cc
These warnings were discovered when I tried to update abseil dependency my project depends on.
For more details take a look at https://github.com/abseil/abseil-cpp/pull/254
=> Solve GCC8 warnings

src/time_zone_format.cc
In this code Windows previously meant Visual C++. This patch extends this to MinGW (both 32 and 64).
Kind regards,
Vladimir.
=> Fixed build under MinGW.

src/time_zone_lookup.cc
It looks like "/etc/localtime" can't be accessed on iOS, so `local_time_zone()` always falls back to UTC.
I used Core Foundation methods that are available on every Apple platform (since OS X 10.0, apparently).
Tested with iOS 10, 11 and 12.1.4
=> Make local_time_zone() work on iOS

src/time_zone_lookup.cc
To allow overriding the timezone with `CFTimeZoneSetDefault` (to run tests)
`CFTimeZoneCopyDefault()` checks if a default timezone is set and if there's none it falls back to the system time zone.
=> Use CFTimeZoneCopyDefault() instead of CFTimeZoneCopySystem()

src/time_zone_lookup.cc
Treat the Apple Core Foundation "default time zone" and the
Android "persist.sys.timezone" property consistently as initial
values for the local time zone (overriding ":localtime").  Then
allow ${TZ} to override that on all platforms.
The only slightly confusing thing is CFTimeZoneCopyDefault()
appears to also heed ${TZ} internally, but that's OK.
=> Update per-platform support for determining the local time zone

BUILD
This broke Abseil's cmake and Bazel builds, eg https://github.com/abseil/abseil-cpp/issues/291
This is required to fix the Bazel builds as well.
=> Link to CoreFoundation in time_zone

include/cctz/civil_time_detail.h, src/civil_time_test.cc, src/time_zone_lookup.cc
In cases where substitution of a 0 for an undefined symbol
would work just fine, we now additionally check if the symbol
is defined.  That is, `#if defined(FOO) && FOO >= N` instead
of just `#if FOO >= N`.  This caters to users of -Wundef.
Note that we don't do this for __cpp_constexpr as we require
C++11, and all C++11 compilers should provide a value for that.
=> Cater to -Wundef by also checking defined() in #if tests

include/cctz/civil_time_detail.h, src/cctz_benchmark.cc
Only do one get_weekday() call and one CivilDay addition per
next_weekday()/prev_weekday() call instead of one pair for
every day between the input and output.
Add benchmarks for get_weekday()/next_weekday()/prev_weekday().
=> A 5X performance improvement in next_weekday()/prev_weekday()

include/cctz/civil_time.h, src/civil_time_test.cc
Previously we suggested `prev_weekday(d, weekday::thursday) + 7`
to get the _following_ Thursday if d is not already a Thursday,
but `next_weekday(d - 1, weekday::thursday)` is more intuitive,
and probably even a little faster.
Similarly for the _previous_ Thursday if d is not already a
Thursday, suggest `prev_weekday(d + 1, weekday::thursday)`
instead of `next_weekday(d, weekday::thursday) - 7`.
=> Change the suggestions for the non-strict next/prev-weekday calls

src/time_zone_libc.cc
The support for "libc:localtime/UTC" uses platform-specific mechanisms
to populate the time_zone::absolute_lookup::offset and abbr fields.
Here we simplify the access to those mechanisms a little, including
better adaptation to the `struct tm` extension fields.
=> Simplify the handling of the tm_gmtoff and tm_zone extension fields

src/time_zone_info.cc
XCode/Clang complains that the constructor to
AndroidZoneInfoSource is unused.
=> Fix -Wunused-member-function warning.

src/time_zone_libc.cc
On platforms where `tm::tm_gmtoff` is wider than an `int`
we risk implicit conversion loss, but we already assume
`int` is at least 32 bits and `tm::tm_gmtoff` should never
exceed about 50k in absolute value, so no actual loss occurs.
=> Add casts to suppress implicit-conversion-loss warnings

src/zone_info_source.cc
By first checking for __has_attribute(weak) we can more easily
support Windows compilers, like "clang-cl", that don't require
the #pragma comment(linker, "/alternatename:...") dance.  That
also means that clang-cl can link with libc++, which uses inline
namespaces in std symbols that would otherwise need special
"alternatename" values.
=> Reverse the checks for __has_attribute(weak) and _MSC_VER

src/time_tool.cc, src/time_zone_fixed.cc
MSVC emits a couple of "C4496 error: strcpy function my be unsafe"
warnings, so, even though the code is actually safe, we tweak things
to avoid strcpy().
Also fully qualify some \<cstring\> calls in time_tool.cc.
Fixed #106 .
=> Avoid strcpy() calls to quash MSVC warnings

src/time_zone_format.cc
POSIX standards require _XOPEN_SOURCE to be defined with any value to
import strptime from time.h. Since the C++ standard doesn't specify
strptime, ctime does not have to be implemented with #include <time.h>.
Therefore, this change adds the include directly.
This PR is an alternative to https://github.com/google/cctz/pull/114
=> Define _XOPEN_SOURCE to import strptime

include/cctz/civil_time.h, include/cctz/civil_time_detail.h, src/civil_time_test.cc, src/time_tool.cc, src/time_zone_format.cc, src/time_zone_lookup_test.cc
Previously `get_weekday()` and `get_weekday()` only took a `civil_day`,
but this allowed them to be called with a `civil_year` or `civil_month`
(due to implicit conversions), while preventing them from being
called with a `civil_hour`, `civil_minute`, or `civil_second`, where
those functions actually make much more sense.  So, convert them
to template functions that accept all civil-time types.
=> Allow get_weekday() and get_yearday() to take all civil-time types

src/time_zone_info.cc
Even though there is no shadowing (if the lambda argument wasn't
"zip", using "zip" in the lambda body would be an error), and it
was nice to use the same name, let's quash the warning.  Fixes #117.
=> Avoid a "-Wshadow-uncaptured-local" warning

include/cctz/civil_time_detail.h
Instead of using `civil_time<T>`-templated functions, simply take
a `civil_second` argument, which will be implicitly realigned from
any other civil-time type.
=> Update #116 to use a civil_second parameter for get_{week,year}day()

src/time_zone_posix.cc
This wasn't a practical problem because the `N` field is a
direct overlay for the `J` field, but that was just luck.
Also `std` qualify all uses of the `<cstdint>` types.
=> Set the correct union field for PosixTransition::N

src/time_zone_impl.cc
time_zone_impl.cc contains a global static std::mutex to protect the mutable time_zone_map.
On platforms where std::mutex's destructor is non-trivial (see https://bugs.llvm.org/show_bug.cgi?id=27658), the global mutex is at risk of the static deinitialization order fiasco.
This CL fixes the issue by using `new` to move the file-scoped std::mutex onto the heap, intentionally leaking it to avoid the static deinitialization order fiasco.
Tested:
% bazel test :all
=> Ensure we don't call destructor for global static time_zone_mutex

src/time_zone_impl.cc
Originally, https://github.com/google/cctz/pull/123 moved time_zone_mutex
into a function to solve both a SDOF issue as well as a performance issue.
The PR was restructured to only fix the SDOF issue, but that
introduced a SIOF issue where time_zone_mutex was moved to a new'd
pointer on the heap instead of a link-time initialized std::mutex.
To resolve the SIOF issue, this PR restores the original behavior of
moving time_zone_mutex into a function. This does introduce an
additional atomic load (or, on MSVC, a TLS access) to check if
the mutex is initialized, but this is not expected to be a hot
code-path since it can potentially hit the disk to load a time zone
definition.
Tested:
% bazel test :all
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
=> Fix SIOF issue by moving time_zone_mutex into function

BUILD, WORKSPACE
Starting with Bazel 1.0 (September 2019), C++ rules will need to be
loaded from the @rules_cc repository. This change adds the required
loads for that.
Pull request for Abseil is
https://github.com/abseil/abseil-cpp/pull/351
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/125)
=> Load @rules_cc for compatibility with Bazel 1.0

src/time_zone_info.cc
- We don't want to discard "file:" more than once.
- Using recursion risks stack overflow.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/128)
=> Modify how a zone-name "file:" prefix is discarded

src/time_zone_impl.cc
Instead of simply forgetting about existing `time_zone::Impl*` entries
in `ClearTimeZoneMapTestOnly()`, move them to a private container,
where they are logically unreachable but not "leaked".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/129)
=> Defeat leak detectors in ClearTimeZoneMapTestOnly()

src/zone_info_source.cc
MinGW is GCC on Windows, so while it asserts __has_attribute(weak),
the Windows linker cannot handle that. Nor does the MinGW compiler
know how to pass "#pragma comment(linker, ...)" to the Windows linker.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/130)
=> Disables the zone_info_source extension under the MinGW compiler

src/time_zone_fixed.cc, src/time_zone_format_test.cc, src/time_zone_info.cc, src/time_zone_lookup_test.cc
Renamed shadowing variables where the new object does not play
the same role as the shadowed object (or type in one case).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/133)
=> style: make some allowances for -Wshadow

include/cctz/time_zone.h, src/cctz_benchmark.cc, src/time_zone_format.cc, src/time_zone_format_test.cc, src/time_zone_lookup_test.cc
%EZ now accepts 'z' in addition to 'Z' as a synonym for +00:00.
%ET is introduced, producing 'T' on output, and accepting 'T'
or 't' on input.  This is for the RFC3339 date-time separator.
Fixes #143.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/144)
=> support parsing 'T' and 'Z' case insensitively

src/time_zone_impl.cc
This means that threads can now be doing lookups while another is
loading data, and that multiple threads can load data at the same
time.
If multiple threads were loading the same data concurrently, all
but one of them would have their work discarded, but this is a
small (and uncommon) price to pay in order to admit lookups while
a load is in progress.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/149)
=> Don't hold a lock while reading zoneinfo data

src/time_zone_format.cc
The zero'th week of the year containing a civil_day may be in the
previous year, so we need to be a little careful not to (negatively)
overflow the year when we do not need to represent such a year in the
final result.  So, use the 400-year calendar equivalence to choose a
more friendly year when computing week numbers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/151)
=> avoid civil_day overflow when computing week numbers

src/time_zone_format.cc, src/time_zone_format_test.cc
Parsing %U/%W conversions with week values in {0, 52, 53} can
slip into the previous/following calendar years, so fail the parse if
the final year value cannot be represented.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/153)
=> check for year overflow when parsing %U/%W conversions

src/time_zone_info.cc, src/time_zone_info.h
In an upcoming release of https://github.com/eggert/tz (probably
2020b), the default value for zic's "-b" (bloat) option will change
from "fat" to "slim". This makes the TZif files smaller by omitting
transitions that were ostensibly only there to work around potential
bugs or incompatibilities in old readers.
TimeZoneInfo::ExtendTransitions() depended on the shape of those
transitions when using the POSIX TZ string to handle instants after
the last transition in the file.
So, update ExtendTransitions() to deal with both TZif varieties.
In the process, remove the logging that tried to alert the user when
those old transition-shape assumptions were found not to hold.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> handle "slim" TZif files in TimeZoneInfo::ExtendTransitions()

src/time_zone_info.cc, src/time_zone_info.h
`GetTransitionType()` returned a transition index via a `uint_fast8_t*`
output parameter, but that value then had to be immediately narrowed to
a `uint_least8_t` struct member.  For clarity, let's just stick with
`uint_least8_t` for the whole process.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/157)
=> Stick with uint_least8_t rather than a (possibly) narrowing conversion.

BUILD
The BUILD file is not the source of truth for the license
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/160)
=> Removes license comment

WORKSPACE
Avoid using the head releases in favor of a named release in
the interest of stability.  We'll have to update occasionally,
but that's OK.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/168)
=> Tie google/googletest and google/benchmark to a recent release

WORKSPACE
It looks like the previous commit snapshot is no longer being
served by `mirror.bazel.build` (and it was over a year old).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/167)
=> Update to a newer version of bazelbuild/rules_cc

src/time_zone_lookup_test.cc
MakeTime.SysSecondsLimits currently assumes that `gmtime_r()` can
handle (64-bit) `time_t` inputs that exercise the full range of the
`tm_year` field on output.  This assumption does not appear to hold
on BSD systems.
In particular, the test assumes `gmtime_t()`, given a `time_t` value
of 67768036191676799, will produce the "largest possible" `struct tm`,
`{tm_year=2147483647 tm_mon=11 tm_mday=31 tm_hour=23 tm_min=59 tm_sec=59}`.
On BSD systems `gmtime_t()` instead returns NULL, which then causes
CCTZ to return a saturated `civil_second` from `time_zone::lookup()`.
So, let's simply omit that expectation on FreeBSD and OpenBSD systems.
Fixes #165.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Disable a "libc:UTC" test expectation that fails on BSD systems

include/cctz/civil_time_detail.h
Do not use mutating operations during constant evaluation of non-mutating operators to avoid triggering an ICE in gcc-5.5
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/174)
=> Workaround gcc-5.5 ICE bug.

src/time_zone_libc.cc
AIX does not provide a `struct tm` field for timezone offset, just like
Solaris so the existing code for that platform can be reused on AIX.
Unfortunately, AIX does not define the `altzone` variable in any header
file so a definition must be defined in this file.
Fixes #176
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/177)
=> Fix tm_gmtoff build failure on AIX

src/time_tool.cc, src/time_zone_fixed.cc, src/time_zone_lookup_test.cc
`cctz::load_time_zone("UTC0", &tz)` now behaves exactly the same as
`cctz::load_time_zone("UTC", &tz)`, allowing `cctz::local_time_zone()`
to "succeed" (i.e., without fallback to "UTC") under `TZ=UTC0`.
This allows for setting `TZ=UTC0` to specify the local timezone as
UTC under both CCTZ and libraries that use POSIX-style `${TZ}` parsing.
Update `time_tool` to use an empty string to request `local_time_zone()`
instead of depending on `load_time_zone("localtime", &tz)` doing the
same thing, which may not work with the configuration of some systems.
This means that `time_tool` now respects `${TZ}`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/185)
=> Add support for cctz::load_time_zone("UTC0", &tz)

src/time_tool.cc
In #185 we avoided depending on `load_time_zone("localtime", &tz)`,
which may not work with the configuration of some systems, by
treating the empty string as a request for `local_time_zone()`.
But it is simpler, clearer, and backwards compatible to use
"localtime" instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/186)
=> Revert time_tool to use "localtime" for the local timezone.

src/time_zone_info.cc, src/time_zone_lookup.cc, src/time_zone_lookup_test.cc
- Implement `FuchsiaZoneInfoSource` to read tzif2 files from their designated locations on Fuchsia systems.
- Implement calls to Fuchsia APIs in `local_time_zone()`.
- Disable a time conversion edge case that is unsupported on Fuchsia.
Bazel does not yet support Fuchsia configs, so these changes must be built and tested internally. See cl/374587662.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/189)
=> Add basic support for Fuchsia

src/time_zone_info.cc
All `FileZoneInfoSource`-derived classes now accept transfer of
of that `unique_ptr`.
Also remove the `FileZoneInfoSource::Open()` code to determine
the length of the zoneinfo file.  We do not need the length when
we read to EOF.
Finally, refactor the new `FuchsiaZoneInfoSource` code a little.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/190)
=> Move raw FILE* values into an auto-closing unique_ptr ASAP.

src/time_zone_info.cc
This is similar to #188, but fixes the issue introduced in #190.
I'm sending a separate change to upgrade to GCC 11 to prevent these
from sneaking in.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/191)
=> Fixes -Wrange-loop-construct warning in GCC 11

CMakeLists.txt
1. When we cross-build to iOS, by default PLATFORM_ID is not set, while APPLE variable is. Without this modification, CoreFoundation is not linked under iOS/tvOS/watchOS, leading to undefined references (at link time of dependent tools).
2. Due to https://cmake.org/cmake/help/latest/policy/CMP0006.html, RUNTIME DESTINATION for executables is not sufficient for iOS/tvOS/watchOS, they need BUNDLE DESTINATION.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/193)
=> CMake: fix cross-build to iOS when tools are enabled

BUILD, WORKSPACE
This is the new way of getting platform constraints
https://github.com/bazelbuild/bazel/issues/8622
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/196)
=> Use the Bazel @platforms repository for platform constraints

include/cctz/time_zone.h
Don't write `min(` or `max(` in headers as this conflicts with a
common Windows macro.  Use parens around the name to interrupt the
token sequence.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/201)
=> Avoid min()/max() macro conflicts

src/time_zone_info.cc
These trigger clang tidy checks when importing into google3: https://clang.llvm.org/extra/clang-tidy/checks/readability-redundant-smartptr-get.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/205)
=> Remove a few redundant calls to `unique_ptr.get()`

src/zone_info_source.cc
This patch changes the linking of 32-bit ARM zone info source to use
the same code as the 32-bit X86 zone info source.
This change is requested in
https://github.com/abseil/abseil-cpp/issues/829 by members of the
Microsoft organization who say it fixes the issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/208)
=> Fix 32-bit ARM builds

include/cctz/civil_time_detail.h
There are two optimizations. The first is to cache the year index while
stepping through 100 year and 4 year intervals in n_day.
The second is an optimization to the year index calculation itself.
The year_index function had been forcing the modulus result to be
non-negative by adding 400 and taking the modulus again. Even with the
multiply&shift technique that compilers use for integer division with
known divisor, this isn't very cheap. Most of the time it should be
faster to do a conditional-move or branch on the modulus results, though
it is possible there are processors where this isn't faster.
Some microbenchmark results:
```
name                                                         old time/op             new time/op             delta
BM_Difference_Days …
```
=> Small microptimization to year_index.

src/time_tool.cc
This change is in support of the go/NULL-termination LSC
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/216)
=> Replace NULL with nullptr

testdata/README.zoneinfo
Provide a switch to use github.com/JodaOrg/global-tz (which reinstates
rules removed from recent versions of the IANA database) as the tzdata
source.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/219)
=> Update the script for generating testdata/zoneinfo.

src/time_zone_format_test.cc
Restrict testing of some extended format/parse specifiers (e.g.,
%k, %l, and %P) to platforms that define `__GLIBC__`.  This means
the tests can run with alternative Linux C run-time libraries,
like https://musl.libc.org/, that do not support those extensions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/220)
=> Limit testing of extended format/parse specifiers to GLIBC

src/time_zone_lookup_test.cc
Further restrict the environments where we know what to expect from
`mktime()`; in particular to `__GLIBC__`.  This means the test will
also be skipped when run with alternative Linux C run-time libraries,
like https://musl.libc.org/.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/221)
=> Limit MakeTime.LocalTimeLibC test to GLIBC

src/time_zone_format.cc
OpenBSD does not expose `vasprintf` when `_XOPEN_SOURCE` is defined, but
`__bsd_locale_fallbacks.h` in the platform libc++ requires this to be
visible, thereby causing a compilation failure. In fact, `strptime` and
`vasprintf` are normally visible without defining any standard-visibility
`#defines`, so don't do anything special here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/224)
=> Buildfix OpenBSD.

src/time_zone_info.cc
Do not look at DST start and end date/time until we know they
have been initialized.  Also add a check that the prevailing
transition matches the POSIX rule for year-round DST.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/229)
=> Fix call placement of recently-introduced AllYearDST()

src/time_zone_info.cc
See https://github.com/eggert/tz/commit/bbbb46c.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/234)
=> cleanup: zic.c no longer tries to "WORK_AROUND_QTBUG_53071"

src/time_zone_info.cc
In theory, leap-second record of version 1 zonefiles is 4 + 4 bytes per record.
https://www.rfc-editor.org/rfc/rfc8536.html#section-3.2
In practice, this commit won't make any difference because we return early at line 437 if hdr.leapcnt != 0.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/236)
=> Fix skipping unused portions in TimeZoneInfo::Load() for version 1 zonefiles

BUILD
Fixing https://github.com/abseil/abseil-cpp/issues/326 by removing a non-working Foundation linkopt for OS X and iOS.
Foundation should now be implicitly added by modern versions of bazel so this will hopefully not be problematic for builds previously affected by https://github.com/abseil/abseil-cpp/issues/291
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/237)
co-authored-by: [devbww](https://github.com/devbww)
=> build: fix cross-platform android builds on OS X

.github/workflows/cifuzz.yml
Add [CIFuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration/) workflow action to have fuzzers build and run on each PR. This is a service offered by OSS-Fuzz where cctz already runs.
CIFuzz can help detect catch regressions and fuzzing build issues early, and has a variety of features (see the URL above). In the current PR the fuzzer is built on a pull request and will run for 300 seconds.
Signed-off-by: David Korczynski <david@adalogics.com>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/238)
=> ci: add CIFuzz github action

CMakeLists.txt
Hi,
Here is a small PR that will help adding this package to Gentoo.
In some cases, it is desirable to run tests but no benchmark.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/cctz/241)
=> Add an option to separate benchmark build from tests

src/time_zone_format_test.cc, src/time_zone_lookup_test.cc
When cctz is imported into Abseil in a nested namespace (absl::time_internal::cctz), GCC 13 considers unqualified calls to cctz::format to be ambiguous with C++20's std::format.
I tried adding a using declaration at the top of the files, but that didn't work.
=> Fully qualify cctz::format in tests

src/time_zone_lookup.cc
The Windows API histrocally didn't use the IANA time zone names, however, Windows 10 introduced the new WinRT Calendar class that returns the IANA identifiers.
This PR uses the new API and gets the local time zone on Windows 10 and later. To maintain binary compatibility with Windows 7 and earlier (down to Windows XP), the DLL and function pointers are dynamically loaded. It still requires the application developer to provide zoneinfo (e.g. setting the TZDIR environment variable).
Issue: #53
Test run:
```
PS C:\src\cctz> [System.Environment]::OSVersion
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
Win32NT             10.0.19045.0 Microsoft Windows NT 10.0.19045.0
PS C:\src\cctz> Set-Timezone "Tokyo Standard Time"
PS C:\src\cctz> …
```
=> local_time_zone: Add Windows support with WinRT

src/time_zone_format_test.cc
Fully qualify another instance of cctz::format() in time_zone_format_test.cc
This is a follow-up to 8b81c2e5cec44f2f9147a9ece35f2fa1fb407049.
Tested during the Abseil import.
=> Fully qualify another instance of cctz::format()

src/time_zone_if.cc, src/time_zone_libc.cc, src/time_zone_lookup_test.cc
Fix the TimeZoneLibC::MakeTime() handling of certain civil times in cases where that is possible. [Some mktime() implementations do not support distinguishing unique/skipped/repeated civil times, so we make no guarantees.]
And to that end, add a clearer note that the "libc:*" zones are for internal testing only, and should not be used otherwise.
Finally, add extra checks to MakeTime.LocalTimeLibC that exercise some of the previously problematic cases.
=> Fix the "libc:localtime" implementation

src/time_zone_libc.cc
To support compiling library with -Werror,-Wshorten-64-to-32 flags
=> Avoid implicit long -> int conversion when calling tm_gmtoff

src/time_zone_format.cc, src/time_zone_libc.cc
This PR adds VxWorks support.
A little code is changed for:
strptime() is not supported by VxWorks.
The time zone variables in VxWorks are: timezone and tzname.
=> Add VxWorks support

include/cctz/time_zone.h
time_zone.h has references to std::femto, which is defined in `<ratio>`. This project currently compiles because this symbol is provided by transitive includes in the C++ library implementation that are not guaranteed to exist.
=> Fix missing include in time_zone.h

src/time_zone_if.cc, src/time_zone_if.h, src/time_zone_impl.cc, src/time_zone_impl.h, src/time_zone_info.cc, src/time_zone_info.h
This can allow environments like Emscripten WebAssembly to strip LoadTimeZone and all of the transitive filesystem code for loading timezones when only UTC is used.
=> Streamline time_zone::Impl::UTC to bypass general LoadTimeZone().

src/time_zone_format.cc, src/time_zone_if.cc, src/time_zone_if.h, src/time_zone_impl.cc, src/time_zone_impl.h, src/time_zone_info.cc, src/time_zone_info.h, src/time_zone_libc.cc, src/time_zone_libc.h, src/time_zone_lookup_test.cc
Follow the direction of #256, which added factory functions for UTC, and add them for named time zones too.  This tightens up the `TimeZoneInfo` and `TimeZoneLibC` interfaces a little, most notably by allowing `TimeZoneInfo::Load(const std::string&)` to become private.  Re-order the implementation as a result (which forms the majority of the diff, sorry).
Also, add a new test to check that a `load_time_zone()` failure results in a `time_zone` that compares equal to `utc_time_zone()`.
Finally, cleanup a couple of unrelated comments.
=> Add factory functions for named time zones

src/time_zone_info.cc, src/time_zone_libc.h
We happened to be picking these up transitively, but we should not depend on that.
=> Add a couple of direct-dependency includes

BUILD
This breaks toolchains that don't add the implicit Foundation linkopt. I can no longer reproduce this building envoy for Android so I'm not sure if we mis-diagnosed the issue, or if it was fixed another way.
https://github.com/google/cctz/pull/237
This reverts commit 5417654582642359a597b273bacaaedcc99f758f.
=> Revert "build: fix cross-platform android builds on OS X (#237)"

src/time_zone_info.cc, src/time_zone_lookup_test.cc
2022g introduced a new zone, America/Ciudad_Juarez, whose "-b slim" form ends in 2022, but with transitions that do not match those that would be generated by the POSIX TZ string used to handle instants in future years.
If we extend the transitions for only 400 years, instants beyond the last generated transition in years equivalent to (2022 mod 400), will be mapped back to 2022, where they could therefore be given the wrong treatment.
So, extend the transitions using the POSIX string for 401 years instead. This means we will always map back to a generated year (in this case, 2023 to 2422).
=> Extend transitions for 401 years

src/time_zone_lookup.cc
Windows SDK added `windows.globalization.h` file from SDK 10.0.10240.0, but MinGW added this file in 10.0.22621.0.
Credit to @veblush for co-developing this fix.
=> Changes the Windows SDK version check to support MingW

BUILD
The layering_check feature ensures that rules that include a header explicitly depend on a rule that exports that header. Compiler support is required, and currently only Clang 16+ supports diagnoses layering_check failures.
The parse_headers feature ensures headers are self-contained by compiling them with -fsyntax-only on supported compilers.
The header_modules feature is Bazel support for modules and is already enabled when CCTZ is included in Abseil. This just reduces the BUILD diff.
Tested with Clang 17
=> Bazel: Support header_modules, layering_check and parse_headers

src/time_zone_info.cc
Added `/config/tzdata` as a canonical path in the
Fuchsia component's namespace.
This is from:
https://fuchsia.dev/fuchsia-src/concepts/process/namespaces#typical_directory_structure
Each directory prefix entry in the list of prefixes that Fuchsia looks for timezone data files is now
explained with a comment.
=> [fuchsia] Adds new tzdata dir, explains all dirs

src/time_zone_info.cc
Even when the last two transitions share a type, we should not discard the last transition as that might change the point at which we start to apply the POSIX spec for future transitions.
This will start to make a difference in zoneinfo files compiled using the 2023d zic for Antarctica/Macquarie, Europe/Riga, Europe/Tallinn, Europe/Vilnius, and Pacific/Norfolk, where we previously would have added daylight-time transitions in years where they did not really apply.
=> Stop trimming "redundant" trailing transitions.

src/time_zone_lookup.cc
See: https://github.com/chromium/chromium/commit/03d8ffbb86e87ee36e2aa6dc8e650dd0a2ba1fe2
The example cited in the code comment from chromium has been removed. It turns out this was never necessary and it is not clear why it was added to chromium in the first place (see the commit message from the commit linked above).
Although this definition of __system_property_get does not cause any issues because it is defined in an anonymous namespace, it is unnecessary and misleading, and we should remove it in favor of the one directly available from libc.so.
=> [Android] Remove unnecessary __system_property_get definition

src/time_zone_libc.cc
Old test checked `defined(_WIN32) || defined(_WIN64)`, which is redundant. `_WIN32` is always defined for `_WIN64` builds as well (https://learn.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-170&redirectedfrom=MSDN):
```
_WIN32 Defined as 1 when the compilation target is 32-bit ARM, 64-bit ARM, x86, or x64. Otherwise, undefined
```
`_CRT_SECURE_NO_WARNINGS` could be defined externally, this code would produce this warning:
```
1>D:\abseil-cpp\absl\time\internal\cctz\src\time_zone_libc.cc(16,9): warning C4005: '_CRT_SECURE_NO_WARNINGS': macro redefinition
```
The PR addresses the issue.
=> Do not redefine _CRT_SECURE_NO_WARNINGS if it's defined

CMakeLists.txt
Follow Google's OSS policy.
Remove other code specific for CMake < 3.16
=> [cmake] Require CMake 3.16

CMakeLists.txt
The output does not help identifiy the issue, the missing dependency is called out in the feature summary anyway.
=> [cmake] Find Benchmark quiet

src/time_zone_info.cc
Found by Clazy (range-loop-reference)
=> Use reference in range-for with non trivial type

src/time_zone_info.cc
/abseil-cpp/absl/time/internal/cctz/src/time_zone_info.cc:559:27: error: loop variable 'prefix' of type 'const std::string&' {aka 'const std::__cxx11::basic_string<char>&'} binds to a temporary constructed from type 'const char* const' [-Werror=range-loop-construct]
559 |   for (const std::string& prefix : prefixes) {
=> Revert "Use reference in range-for with non trivial type"

src/time_zone_lookup.cc
This fixes the following compiler errors.
time_zone_lookup.cc:78:34: error: 'WindowsCreateStringReference' was not declared in this scope time_zone_lookup.cc:84:34: error: 'WindowsDeleteString' was not declared in this scope time_zone_lookup.cc:90:34: error: 'WindowsGetStringRawBuffer' was not declared in this scope
Also, official documentation suggests to include the winstring.h header. https://learn.microsoft.com/en-us/windows/win32/api/winstring/nf-winstring-windowsgetstringrawbuffer
=> Fix mingw compiler error due to missing function declaration

src/time_zone_lookup.cc
Fuchsia has a code snippet that uses its FIDL IPC mechanism to request time zone information from the host.
The generated FIDL bindings have been changed since this code was first written from the "high level" (HL) CPP bindings to the "new" CPP bindings.
We are now migrating external code to remove the HL CPP bindings to allow FIDL to continue development.  No other platforms should be affected, since the changes are in the sections of the code that is conditionally compiled only when Fuchsia is the target platform.
=> [fuchsia] Updates the FIDL bindings in Fuchsia-specific code

MODULE.bazel, README.md
Cleanup a couple of things I noticed during a recent PR:
- Update the 'platforms' version to match the root module.
- Update the documented minimum cmake requirement to match CMakeLists.txt.
=> Miscellaneous cleanup for MODULE.bazel and README.md

include/cctz/time_zone.h
Fix typo in include/cctz/time_zone.h
=> Fix typo in time_zone.h

src/time_zone_lookup.cc
This reworks our previous commit (1bb996caf91effbf3e74ac444b0945b6360a8822), which aimed to address #53 by implementing `cctz::local_time_zone` with WinRT API on Windows.
The issue is there is no guarantee that `RoInitialize` can be safely called when `cctz::local_time_zone` gets called. In theory cctz can have its own thread to safely call `RoInitialize` and WinRT APIs, but such an approach would make the code much more complex and fragile.
This commit takes advantage of newly exposed ICU APIs that do not require COM/WinRT initialization on Windows 10 1903 and later.
* https://devblogs.microsoft.com/oldnewthing/20210527-00/?p=105255
To maintain binary compatibility with earlier versions of Windows, the DLL and function pointer are still loaded dynamically.
Closes #315.
=> Remove WinRT deps from `cctz::local_time_zone`

src/time_zone_lookup.cc
This commit attempts to fix the build failure reported in https://github.com/google/cctz/pull/316#issuecomment-2866482102, which is a consequence of my previous commit (2ebbe0d8a2771f9899839765fe3e651bd2b55382).
With this commit relevant Win32 macros are overridden only while including `<icu.h>`. This commit also overrides `_WIN32_WINNT` to be consistent with `NTDDI_VERSION`.
=> Speculative fix for "No Target Architecture" error

include/cctz/civil_time_detail.h
`error: 'array-bounds' attribute directive ignored [-Werror=attributes]`
=> Fix GCC attribute warning introduced by #319
